var group___l_c_i___r_e_s_o_u_r_c_e =
[
    [ "alloc_packet_pool", "d2/dab/group___l_c_i___a_l_l_o_c___p_a_c_k_e_t___p_o_o_l.html", "d2/dab/group___l_c_i___a_l_l_o_c___p_a_c_k_e_t___p_o_o_l" ],
    [ "free_packet_pool", "d6/d49/group___l_c_i___f_r_e_e___p_a_c_k_e_t___p_o_o_l.html", "d6/d49/group___l_c_i___f_r_e_e___p_a_c_k_e_t___p_o_o_l" ],
    [ "register_packet_pool", "df/dd6/group___l_c_i___r_e_g_i_s_t_e_r___p_a_c_k_e_t___p_o_o_l.html", "df/dd6/group___l_c_i___r_e_g_i_s_t_e_r___p_a_c_k_e_t___p_o_o_l" ],
    [ "deregister_packet_pool", "d5/d59/group___l_c_i___d_e_r_e_g_i_s_t_e_r___p_a_c_k_e_t___p_o_o_l.html", "d5/d59/group___l_c_i___d_e_r_e_g_i_s_t_e_r___p_a_c_k_e_t___p_o_o_l" ],
    [ "get_upacket", "df/de2/group___l_c_i___g_e_t___u_p_a_c_k_e_t.html", "df/de2/group___l_c_i___g_e_t___u_p_a_c_k_e_t" ],
    [ "put_upacket", "d9/d20/group___l_c_i___p_u_t___u_p_a_c_k_e_t.html", "d9/d20/group___l_c_i___p_u_t___u_p_a_c_k_e_t" ],
    [ "alloc_matching_engine", "d8/df1/group___l_c_i___a_l_l_o_c___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "d8/df1/group___l_c_i___a_l_l_o_c___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ],
    [ "free_matching_engine", "de/d9b/group___l_c_i___f_r_e_e___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "de/d9b/group___l_c_i___f_r_e_e___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ],
    [ "matching_engine_insert", "d7/d93/group___l_c_i___m_a_t_c_h_i_n_g___e_n_g_i_n_e___i_n_s_e_r_t.html", "d7/d93/group___l_c_i___m_a_t_c_h_i_n_g___e_n_g_i_n_e___i_n_s_e_r_t" ],
    [ "set_allocator", "d0/d59/group___l_c_i___s_e_t___a_l_l_o_c_a_t_o_r.html", "d0/d59/group___l_c_i___s_e_t___a_l_l_o_c_a_t_o_r" ],
    [ "get_default_net_context", "d3/d74/group___l_c_i___g_e_t___d_e_f_a_u_l_t___n_e_t___c_o_n_t_e_x_t.html", "d3/d74/group___l_c_i___g_e_t___d_e_f_a_u_l_t___n_e_t___c_o_n_t_e_x_t" ],
    [ "get_default_device", "d4/d41/group___l_c_i___g_e_t___d_e_f_a_u_l_t___d_e_v_i_c_e.html", "d4/d41/group___l_c_i___g_e_t___d_e_f_a_u_l_t___d_e_v_i_c_e" ],
    [ "get_default_endpoint", "d9/d95/group___l_c_i___g_e_t___d_e_f_a_u_l_t___e_n_d_p_o_i_n_t.html", "d9/d95/group___l_c_i___g_e_t___d_e_f_a_u_l_t___e_n_d_p_o_i_n_t" ],
    [ "get_default_packet_pool", "d5/dfb/group___l_c_i___g_e_t___d_e_f_a_u_l_t___p_a_c_k_e_t___p_o_o_l.html", "d5/dfb/group___l_c_i___g_e_t___d_e_f_a_u_l_t___p_a_c_k_e_t___p_o_o_l" ],
    [ "get_default_matching_engine", "d2/de3/group___l_c_i___g_e_t___d_e_f_a_u_l_t___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "d2/de3/group___l_c_i___g_e_t___d_e_f_a_u_l_t___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ],
    [ "alloc_net_context", "d6/df7/group___l_c_i___a_l_l_o_c___n_e_t___c_o_n_t_e_x_t.html", "d6/df7/group___l_c_i___a_l_l_o_c___n_e_t___c_o_n_t_e_x_t" ],
    [ "free_net_context", "d5/d35/group___l_c_i___f_r_e_e___n_e_t___c_o_n_t_e_x_t.html", "d5/d35/group___l_c_i___f_r_e_e___n_e_t___c_o_n_t_e_x_t" ],
    [ "alloc_device", "d0/d5b/group___l_c_i___a_l_l_o_c___d_e_v_i_c_e.html", "d0/d5b/group___l_c_i___a_l_l_o_c___d_e_v_i_c_e" ],
    [ "free_device", "d6/d75/group___l_c_i___f_r_e_e___d_e_v_i_c_e.html", "d6/d75/group___l_c_i___f_r_e_e___d_e_v_i_c_e" ],
    [ "alloc_endpoint", "d9/d89/group___l_c_i___a_l_l_o_c___e_n_d_p_o_i_n_t.html", "d9/d89/group___l_c_i___a_l_l_o_c___e_n_d_p_o_i_n_t" ],
    [ "free_endpoint", "d6/d02/group___l_c_i___f_r_e_e___e_n_d_p_o_i_n_t.html", "d6/d02/group___l_c_i___f_r_e_e___e_n_d_p_o_i_n_t" ],
    [ "RESOURCE packet_pool", "d4/d73/group___l_c_i___p_a_c_k_e_t___p_o_o_l.html", "d4/d73/group___l_c_i___p_a_c_k_e_t___p_o_o_l" ],
    [ "RESOURCE matching_engine", "dc/d15/group___l_c_i___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "dc/d15/group___l_c_i___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ],
    [ "RESOURCE net_context", "d7/dc1/group___l_c_i___n_e_t___c_o_n_t_e_x_t.html", "d7/dc1/group___l_c_i___n_e_t___c_o_n_t_e_x_t" ],
    [ "RESOURCE device", "d9/d14/group___l_c_i___d_e_v_i_c_e.html", "d9/d14/group___l_c_i___d_e_v_i_c_e" ],
    [ "RESOURCE endpoint", "d0/d37/group___l_c_i___e_n_d_p_o_i_n_t.html", "d0/d37/group___l_c_i___e_n_d_p_o_i_n_t" ]
];