var group___l_c_i___r_e_s_o_u_r_c_e =
[
    [ "RESOURCE runtime", "db/da1/group___l_c_i___r_u_n_t_i_m_e.html", "db/da1/group___l_c_i___r_u_n_t_i_m_e" ],
    [ "alloc_runtime", "d8/d8e/group___l_c_i___a_l_l_o_c___r_u_n_t_i_m_e.html", "d8/d8e/group___l_c_i___a_l_l_o_c___r_u_n_t_i_m_e" ],
    [ "free_runtime", "d7/de6/group___l_c_i___f_r_e_e___r_u_n_t_i_m_e.html", "d7/de6/group___l_c_i___f_r_e_e___r_u_n_t_i_m_e" ],
    [ "g_runtime_init", "db/db7/group___l_c_i___g___r_u_n_t_i_m_e___i_n_i_t.html", "db/db7/group___l_c_i___g___r_u_n_t_i_m_e___i_n_i_t" ],
    [ "g_runtime_fina", "db/d4a/group___l_c_i___g___r_u_n_t_i_m_e___f_i_n_a.html", "db/d4a/group___l_c_i___g___r_u_n_t_i_m_e___f_i_n_a" ],
    [ "get_g_runtime", "d9/d33/group___l_c_i___g_e_t___g___r_u_n_t_i_m_e.html", "d9/d33/group___l_c_i___g_e_t___g___r_u_n_t_i_m_e" ],
    [ "RESOURCE net_context", "d7/dc1/group___l_c_i___n_e_t___c_o_n_t_e_x_t.html", "d7/dc1/group___l_c_i___n_e_t___c_o_n_t_e_x_t" ],
    [ "alloc_net_context", "d6/df7/group___l_c_i___a_l_l_o_c___n_e_t___c_o_n_t_e_x_t.html", "d6/df7/group___l_c_i___a_l_l_o_c___n_e_t___c_o_n_t_e_x_t" ],
    [ "free_net_context", "d5/d35/group___l_c_i___f_r_e_e___n_e_t___c_o_n_t_e_x_t.html", "d5/d35/group___l_c_i___f_r_e_e___n_e_t___c_o_n_t_e_x_t" ],
    [ "RESOURCE device", "d9/d14/group___l_c_i___d_e_v_i_c_e.html", "d9/d14/group___l_c_i___d_e_v_i_c_e" ],
    [ "alloc_device", "d0/d5b/group___l_c_i___a_l_l_o_c___d_e_v_i_c_e.html", "d0/d5b/group___l_c_i___a_l_l_o_c___d_e_v_i_c_e" ],
    [ "free_device", "d6/d75/group___l_c_i___f_r_e_e___d_e_v_i_c_e.html", "d6/d75/group___l_c_i___f_r_e_e___d_e_v_i_c_e" ],
    [ "RESOURCE endpoint", "d0/d37/group___l_c_i___e_n_d_p_o_i_n_t.html", "d0/d37/group___l_c_i___e_n_d_p_o_i_n_t" ],
    [ "alloc_endpoint", "d9/d89/group___l_c_i___a_l_l_o_c___e_n_d_p_o_i_n_t.html", "d9/d89/group___l_c_i___a_l_l_o_c___e_n_d_p_o_i_n_t" ],
    [ "free_endpoint", "d6/d02/group___l_c_i___f_r_e_e___e_n_d_p_o_i_n_t.html", "d6/d02/group___l_c_i___f_r_e_e___e_n_d_p_o_i_n_t" ],
    [ "RESOURCE packet_pool", "d4/d73/group___l_c_i___p_a_c_k_e_t___p_o_o_l.html", "d4/d73/group___l_c_i___p_a_c_k_e_t___p_o_o_l" ],
    [ "alloc_packet_pool", "d2/dab/group___l_c_i___a_l_l_o_c___p_a_c_k_e_t___p_o_o_l.html", "d2/dab/group___l_c_i___a_l_l_o_c___p_a_c_k_e_t___p_o_o_l" ],
    [ "free_packet_pool", "d6/d49/group___l_c_i___f_r_e_e___p_a_c_k_e_t___p_o_o_l.html", "d6/d49/group___l_c_i___f_r_e_e___p_a_c_k_e_t___p_o_o_l" ],
    [ "bind_packet_pool", "de/da0/group___l_c_i___b_i_n_d___p_a_c_k_e_t___p_o_o_l.html", "de/da0/group___l_c_i___b_i_n_d___p_a_c_k_e_t___p_o_o_l" ],
    [ "unbind_packet_pool", "d3/d2e/group___l_c_i___u_n_b_i_n_d___p_a_c_k_e_t___p_o_o_l.html", "d3/d2e/group___l_c_i___u_n_b_i_n_d___p_a_c_k_e_t___p_o_o_l" ],
    [ "RESOURCE matching_engine", "dc/d15/group___l_c_i___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "dc/d15/group___l_c_i___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ],
    [ "alloc_matching_engine", "d8/df1/group___l_c_i___a_l_l_o_c___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "d8/df1/group___l_c_i___a_l_l_o_c___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ],
    [ "free_matching_engine", "de/d9b/group___l_c_i___f_r_e_e___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "de/d9b/group___l_c_i___f_r_e_e___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ],
    [ "get_default_net_context", "d3/d74/group___l_c_i___g_e_t___d_e_f_a_u_l_t___n_e_t___c_o_n_t_e_x_t.html", "d3/d74/group___l_c_i___g_e_t___d_e_f_a_u_l_t___n_e_t___c_o_n_t_e_x_t" ],
    [ "get_default_device", "d4/d41/group___l_c_i___g_e_t___d_e_f_a_u_l_t___d_e_v_i_c_e.html", "d4/d41/group___l_c_i___g_e_t___d_e_f_a_u_l_t___d_e_v_i_c_e" ],
    [ "get_default_endpoint", "d9/d95/group___l_c_i___g_e_t___d_e_f_a_u_l_t___e_n_d_p_o_i_n_t.html", "d9/d95/group___l_c_i___g_e_t___d_e_f_a_u_l_t___e_n_d_p_o_i_n_t" ],
    [ "get_default_packet_pool", "d5/dfb/group___l_c_i___g_e_t___d_e_f_a_u_l_t___p_a_c_k_e_t___p_o_o_l.html", "d5/dfb/group___l_c_i___g_e_t___d_e_f_a_u_l_t___p_a_c_k_e_t___p_o_o_l" ],
    [ "get_default_matching_engine", "d2/de3/group___l_c_i___g_e_t___d_e_f_a_u_l_t___m_a_t_c_h_i_n_g___e_n_g_i_n_e.html", "d2/de3/group___l_c_i___g_e_t___d_e_f_a_u_l_t___m_a_t_c_h_i_n_g___e_n_g_i_n_e" ]
];