var searchData=
[
  ['g_5fruntime_5ffina_0',['g_runtime_fina',['../d9/d15/group__LCI__G__RUNTIME__FINA.html',1,'']]],
  ['g_5fruntime_5finit_1',['g_runtime_init',['../de/d1b/group__LCI__G__RUNTIME__INIT.html',1,'']]],
  ['get_5fallocator_2',['get_allocator',['../d6/d00/group__LCI__GET__ALLOCATOR.html',1,'']]],
  ['get_5fdefault_5fdevice_3',['get_default_device',['../df/d10/group__LCI__GET__DEFAULT__DEVICE.html',1,'']]],
  ['get_5fdefault_5fendpoint_4',['get_default_endpoint',['../d3/d5b/group__LCI__GET__DEFAULT__ENDPOINT.html',1,'']]],
  ['get_5fdefault_5fmatching_5fengine_5',['get_default_matching_engine',['../d8/dd9/group__LCI__GET__DEFAULT__MATCHING__ENGINE.html',1,'']]],
  ['get_5fdefault_5fnet_5fcontext_6',['get_default_net_context',['../d9/d24/group__LCI__GET__DEFAULT__NET__CONTEXT.html',1,'']]],
  ['get_5fdefault_5fpacket_5fpool_7',['get_default_packet_pool',['../df/d00/group__LCI__GET__DEFAULT__PACKET__POOL.html',1,'']]],
  ['get_5fg_5fruntime_8',['get_g_runtime',['../d2/d5e/group__LCI__GET__G__RUNTIME.html',1,'']]],
  ['get_5fmax_5fbcopy_5fsize_9',['get_max_bcopy_size',['../dc/d9c/group__LCI__GET__MAX__BCOPY__SIZE.html',1,'']]],
  ['get_5frmr_10',['get_rmr',['../d7/d54/group__LCI__GET__RMR.html',1,'']]],
  ['get_5fupacket_11',['get_upacket',['../d4/dc1/group__LCI__GET__UPACKET.html',1,'']]],
  ['graph_5fadd_5fedge_12',['graph_add_edge',['../d7/d55/group__LCI__GRAPH__ADD__EDGE.html',1,'']]],
  ['graph_5fadd_5fnode_13',['graph_add_node',['../df/df5/group__LCI__GRAPH__ADD__NODE.html',1,'']]],
  ['graph_5fnode_5fmark_5fcomplete_14',['graph_node_mark_complete',['../d1/d28/group__LCI__GRAPH__NODE__MARK__COMPLETE.html',1,'']]],
  ['graph_5fstart_15',['graph_start',['../dd/dcb/group__LCI__GRAPH__START.html',1,'']]],
  ['graph_5ftest_16',['graph_test',['../dd/dad/group__LCI__GRAPH__TEST.html',1,'']]]
];
